apiVersion: v1
kind: Service
metadata:
  name: load-balancer-backend
  namespace: default
  labels:
    app: crowdcontract-backend
spec:
  type: LoadBalancer
  ports:
  - port: 5051
    targetPort: 5051
    protocol: TCP
    nodePort: 31002
  selector:
    app: crowdcontract-backend
