apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: default
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL3ByYXRodmlyYWo6MTIzNEBkYi1zZXJ2aWNlOjI3MDE3L2Nyb3dkY29udHJhY3Q=
  JWT_SECRET_KEY: N2RlNGFmZDUzYmE2ZWFlNTg0ZTBiNjI4MWJlYTIwMzBkOTlhNTk3MWM2NTg1YTJiOTNkZGMyMDZkY2ZmMjcxNjUxYjQ0NDcyY2ZiNTRhY2YwMWNiNzZiNmViOGEyZDljYWEwMjUxYTNhNDBlN2U2NjY0NzU4MjJhMTFjN2NlODk=
  AES_SECRET_KEY: MmE5NTM5ODJlMzM0NzViZTk1M2UzY2FkYWEyYjExZTE1YTc3OTAyOTllNWJlMzZlNDAyMmIxZTg0ZDNkNDk1YTI3MzgxN2IxOGE4NTI0NmQ2NDE0ZTYyZDA2MmQ2MzM2NTRlY2QzODc2ODQxYjcxNGU3OGQ2NzY1Zjg2NDgwMDY=
  PORT: NTA1MQ==
  SALT_ROUNDS: NQ==
