apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: default
  labels:
    app: crowdcontract-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31001
  selector:
    app: crowdcontract-frontend
