version = 1

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = [
    "/client/Dockerfile",
    "/server/Dockerfile"
  ]
