---
name: testAndCreateDockerImage
run-name: testAndCreateDockerImage 🚀
on:
  push:
    paths:
      # - 'client/**'
    branches:
      - main
      
jobs:
  build-frontend-push-img-to-Dockerhub:
    name: build dist for nginx container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: build frontend
        run: |
          cd client
          echo "VITE_AES_SECRET_KEY='${{secrets.AES_SECRET_KEY}}'
                VITE_API_URL=http://${{secrets.AWS_IP}}:5051" > .env
          cat .env
          npm install
          npm run build
      - name: Archive /dist as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: client/dist
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: copy dist to . from Artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
        
      - name: build and push to DockerHub
        run: |
          docker buildx build --platform linux/amd64,linux/arm64/v8 --push --tag prathvirajbn/crowdcontract-frontend:latest ./client

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
