---
- hosts: local
  tasks:
    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes
          - jmespath
    
    - name: Create Mongo DB Volume
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition: "{{ lookup('file', '../deployments/db-volumes.yaml')}}"

    - name: Create Mongo DB Volume Claim
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition: "{{ lookup('file', '../deployments/db-volume-claim.yaml')}}"
        
    - name: Create DB Secrets
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition: "{{ lookup('file', '../deployments/db-secrets.yaml')}}"

    - name: Create DB Deployment
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition: "{{ lookup('file', '../deployments/db-deployment.yaml')}}"
    
    - name: Create DB Service
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition: "{{ lookup('file', '../deployments/db-service.yaml')}}"
        
    - name: Create Backend Secret
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition: "{{ lookup('file', '../deployments/backend-secret.yaml')}}"
    
    - name: Delete previous backend deployment
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      shell: kubectl delete deploy crowdcontract-backend --kubeconfig "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        
    - name: Create a Backend Deployment object from an inline definition
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition: "{{ lookup('file', '../deployments/backend-deployment.yaml')}}"

    - name: Create a Backend service object
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition: "{{ lookup('file', '../deployments/backend-service.yaml')}}"
        
    - name: Delete previous frontend deployment
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      shell: kubectl delete deploy crowdcontract-frontend --kubeconfig "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      
    - name: Create a Frontend Deployment object from an inline definition
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition: "{{ lookup('file', '../deployments/deployment.yaml')}}"

    - name: Create a Frontend service object
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition: "{{ lookup('file', '../deployments/load-balancer.yaml')}}"
